version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeOrgnTest3
  gitServerName: jayeshsahu
  gitUrl: https://github.com/jayeshsahu/EdgeOrgnTest3
  gitUsername: jayeshsahu
  gitBranch: main
